name: Build and Push Image

on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: Homelab
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ github.REPOSITORY }}
      - name: build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
  
  update_deploy_repo:
    runs-on: ubuntu-latest
    needs: push_to_registry
    name: update deploy repo image tag
    steps:
      - name: checkout deploy repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.REPOSITORY }}-deploy
          ref: refs/heads/main
          token: ${{ secrets.AUTH_TOKEN }}
      - name: set up kustomize
        uses: imranismail/setup-kustomize@v1
      - run: |
          cd base && kustomize edit set image myapp=${{ env.IMAGE_NAME }}:${{ github.SHA }} && cat kustomization.yaml
      - run: |
          git config user.name ${{ github.REPOSITORY_OWNER }}
          git config user.email ${{ secrets.EMAIL }}
          git add .
          git commit -m "bump ${{ env.IMAGE_NAME }} image tag to ${{ github.SHA }}"
          git push https://${{ secrets.AUTH_TOKEN }}@github.com/${{ github.REPOSITORY }}-deploy.git

