name: build-image

on:
  push:
    branches-ignore: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Homelab
    steps:
      - name: build image
        id: build-and-publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
