name: Build Push Sign

on:
  push:
    branches: ["*"]
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
  REGISTRY: docker.io
jobs:
  push_to_registry:
    permissions:
      packages: write
      id-token: write
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: Homelab
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.REPOSITORY }}
      - name: build and push Docker image
        id: build-and-publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
      - uses: sigstore/cosign-installer@main
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: verify the signed Docker image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign verify -output text ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  # update_deploy_repo:
  #   runs-on: ubuntu-latest
  #   needs: push_to_registry
  #   name: update deploy repo image tag
  #   environment: Homelab
  #   steps:
  #     - name: checkout deploy repo
  #       uses: actions/checkout@master
  #       with:
  #         repository: ${{ github.REPOSITORY }}-deploy
  #         ref: refs/heads/main
  #         token: ${{ secrets.AUTH_TOKEN }}
  #     - name: set up kustomize
  #       uses: imranismail/setup-kustomize@v1
  #     - run: |
  #         cd base && kustomize edit set image myapp=${{ env.IMAGE_NAME }}:${{ github.SHA }} && cat kustomization.yaml
  #     - run: |
  #         git config user.name ${{ github.REPOSITORY_OWNER }}
  #         git config user.email ${{ secrets.EMAIL }}
  #         git add .
  #         git commit -m "bump ${{ env.IMAGE_NAME }} image tag to ${{ github.SHA }}"
  #         git push https://${{ secrets.AUTH_TOKEN }}@github.com/${{ github.REPOSITORY }}-deploy.git
