name: Build Push Sign

on:
  push:
    branches: ["main"]
env:
  IMAGE_PATH: ghcr.io/kdwils/go-hello
jobs:
  push_to_registry:
    permissions:
      packages: write
      id-token: write
    name: build-push-sign
    runs-on: ubuntu-latest
    environment: Homelab
    steps:
      - uses: actions/checkout@v2

      - name: log in to ghcr
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_PATH }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push Docker image
        id: build-and-publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.IMAGE_PATH }}:${{ github.SHA }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: sigstore/cosign-installer@main

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign ${{ env.IMAGE_PATH }}:${{ github.SHA }}

      - name: verify the signed Docker image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign verify -output text  ${{ env.IMAGE_PATH }}:${{ github.SHA }}

  update_deploy_repo:
    runs-on: ubuntu-latest
    needs: push_to_registry
    name: update deploy repo image tag
    environment: Homelab
    steps:
      - name: checkout deploy repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.REPOSITORY }}-deploy
          ref: refs/heads/main
          token: ${{ secrets.AUTH_TOKEN }}

      - uses: imranismail/setup-kustomize@v1

      - run: |
          cd base && kustomize edit set image myapp=${{ env.IMAGE_PATH }}:${{ github.SHA }} && cat kustomization.yaml

      - run: |
          git config --global user.name ${{ github.REPOSITORY_OWNER }}
          git config --global user.email ${{ secrets.EMAIL }}
          git commit -am "bump ${{ env.IMAGE_PATH }} image tag to ${{ github.SHA }}"
          git push
