name: Build Push Sign
on:
  push:
    branches: ["main"]
jobs:
  build-push-sign:
    uses: kdwils/homelab-workflow/.github/workflows/build-push-sign.yml@main
    secrets: inherit
    with:
      image: kdwils/go-hello
      registry: ghcr.io
      environment: Homelab
      platforms: linux/amd64,linux/arm64
