name: Build Push Sign
on:
  push:
    branches: ["main"]
jobs:
  ci:
    uses: kdwils/homelab-workflow/.github/workflows/build-push-sign.yml@main
    secrets: inherit
    with:
      image: go-hello
      registry: ghcr.io
      environment: Homelab
